### ISSUE TITLE
Broken links in the README?

### ISSUE THREAD

**Issue by xyzshantaram** [Andonome/core#1]
The links to built versions of the book link to ttrpgs.org/share, but there are no files on that website. Is there another place the PDFs can be downloaded from?

**Comment by Andonome** [comment]
I broke the website. I'll fix it soon.

Meanwhile, here's a link to the [pdf](https://gitlab.com/bindrpg/core/-/jobs/1594528145/artifacts/download?file_type=archive).

You can also make it by opening the project and typing `make`. The dependencies are `texlive-full` (or `texlive-most` for arch), `inkscape`, and `git-lfs`.

Thanks for having a look!

**Comment by Andonome** [comment]
The links are working again.

**Comment by xyzshantaram** [comment]
Thanks a bunch! I struggled for a while getting it to build but couldn't figure out what TeX package I needed for `glossaries.sty`.

> Thanks for having a look!

I was really excited to find an open-source TTRPG system, so thank _you_! This is awesome, and I'll probably be playing Adventures in Fenestra with some friends soon, and passing on any feedback we have.

**Comment by Andonome** [comment]
That's wonderful to hear. I'd be delighted to hear any and all feedback. 

The glossaries package is glossaries-extra, but you might also try texlive-full, which should have all TeX packages. 


On 28 September 2021 12:02:55 CEST, Siddharth Singh ***@***.***> wrote:
>Thanks a bunch! I struggled for a while getting it to build but
>couldn't figure out what TeX package I needed for `glossaries.sty`.
>
>> Thanks for having a look!
>
>I was really excited to find an open-source TTRPG system, so thank
>_you_! This is awesome, and I'll probably be playing Adventures in
>Fenestra with some friends soon, and passing on any feedback we have.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Andonome/core/issues/1#issuecomment-929042745

-- Sent from /e/ Mail.
